### ISSUE TITLE
Delete previous image and upload new

### ISSUE THREAD

**Issue by Gianluigi081** [cloudinary-labs/cloudinary-laravel#67]
if($request->hasFile('image')){

            $public_id = Cloudinary::upload('public_id');

            $url = Storage::disk('cloudinary')->url($public_id);
            
            $image_exist = Category::select('image')->where($public_id);

            Cloudinary::destroy($image_exist);

            Cloudinary::upload($request->file('image')->getRealPath(), ['folder' => 'Categories',]);

            $image = $request->file('image')->getRealPath();
        }

I have also tried like this:

            Cloudinary::destroy($article->image);
            
            $article['image'] = Cloudinary::upload($request->file('image')->getRealPath(),[
                'folder' => 'Articles',
            ])->getSecurePath();
            

And so this method works but then it doesn't show me the images in Laravel, but if I delete and update the image in Cloudinary:

          if($request->hasFile('image')){
           
            Cloudinary::destroy($article->image);
            
           
            $article['image'] = Cloudinary::upload($request->file('image')->getRealPath(),[
                'folder' => 'Articles',
            ])->getPublicId();
            
        }

**Comment by Gianluigi081** [comment]
solution:

1. First split the array by /, then get the last position and split it to remove the .jpg
2. In this way the public id is obtained

<!DOCTYPE html>
<html>
<body>

<?php

$string = "https://res.cloudinary.com/djoqnuant/image/upload/v1648822921/Profiles/qttjxqfcfhrwttzyahvo.jpg";

$token = explode('/', $string); 
 
echo '<pre>';
var_dump($token);
echo '</pre>';

//To keep only the last position, which in this case would be 8 rest -1

$token2 = explode('.', $token[sizeof($token)-1]);

echo '<pre>';

var_dump($token2[0]);
echo '</pre>';

?>

</body>
</html>

In Laravel, to delete we use the Cloudinary::destroy('NameFolder/$token[0]) method. The name of the folder will go as long as it is not in the root.

**Comment by fuad4web** [comment]
I also have issue with Cloudinary delete but its now resolved
am able to get the public id like this:

// Extract the public ID from the URL
$publicId = pathinfo($imageUrl, PATHINFO_FILENAME);

whie wanting to delete it i tried this as per Cloudinary documentation:
Cloudinary::destroy($publicId);

But it didn't work out why? Its because i have the image inside "Property Images" folder created in my Cloudinary account so i have to resought to this way before it works:

use CloudinaryLabs\CloudinaryLaravel\Facades\Cloudinary; //my Import at top of the file

Cloudinary::destroy('Property Images/'.$publicId);

If you know you are saving into a Folder, try and always append the folder name like that before the $public id
